### ISSUE TITLE
VnV Review: Section 4.2.1, Is it functional or non-functional

### ISSUE THREAD

**Issue by morteza-im** [FasilCheema/OptimizationLibrary#15]
The implementation and testing of algorithms like DFP, FRCG, and BFGS are integral functional requirements for the project. However, in section 4.2.1, the testing approach primarily focuses on accuracy without explicitly addressing the verification of the correct implementation of these algorithms. It's essential to recognize that checking the relative error serves more as a validation of the algorithm's correct implementation rather than assessing its accuracy. So maybe this part should move to functional requirements.

**Comment by FasilCheema** [comment]
There is a solid point to be made for this move. However, in accordance with the documentation provided it seems that for a library in our case there are many cases (much more often than not) where our solution will not be correct. This is due to the nature of the inputs and computational feasibility restrictions. For this reason the relative error of our solution is more of a quality of our solution as opposed to the library core functionality. It is trivial to make our library output nonsense and hence the correctness of the solution is not the library's responsibility if the inputs provided are not theoretically sound.
