### ISSUE TITLE
Please look at my problem statement 

### ISSUE THREAD

**Issue by FasilCheema** [FasilCheema/OptimizationLibrary#2]
Dr Smith please have a look at the problem statement

**Comment by smiths** [comment]
Feedback:

- in the future provide a link the [document](https://github.com/FasilCheema/OptimizationLibrary/blob/main/docs/ProblemStatementAndGoals/ProblemStatement.pdf) to be reviewed
- the project is very ambitious.  We will need to monitor the scope as the term proceeds to make sure that it is feasible.
- you will be documenting and implementing a library, not a program.  You'll want to keep this in mind as you do your work.  It doesn't make a big difference in the documentation, but occasionally you need to clarify the distinction
- you will be documenting a family of algorithms, rather than a single algorithm.  This is also something that you'll need to keep in mind in your documentation.  You should look at the Commonality Analysis (CA) document as a template to follow for your project.  You will need to identify the commonalities and variabilities, along with the parameters of variation
- Your problem statement would benefit from an abstract equation that defines optimization
- Your problem statement would benefit from links to existing optimization libraries

I'm looking forward to seeing what you create this term.

Project approved.  :smile:

You hadn't created a row in Repos.csv, so I started one for you to indicate the project approval.  Please update the Repos.csv file with the other required information.
