### ISSUE TITLE
Reevaluate Placement of Input Verification Module

### ISSUE THREAD

**Issue by morteza-im** [FasilCheema/OptimizationLibrary#28]
The Input Verification Module (M8) is currently categorized under the Software Decision Module. However, upon review, it seems that its functionality aligns more closely with a Behavior-Hiding Module, as it primarily deals with verifying input data and detecting format issues rather than making design decisions based on mathematical theorems or physical facts. Also, Its secret is mentioned in SRS.

**Comment by FasilCheema** [comment]
This is a concern shared with Dr Smith. I kept it as a software decision because it terminates the program and thus makes a critical design decision if the inputs are invalid. I may reconsider this though process, but for this particular case the inputs being of appropriate dimensionality is a strict mathematical constraint based in mathematical derivations and not simply formatting. Further, these issues are not simply detected by numpy causing a runtime error. There are numerous cases where the dimensionality may not match up and numpy still executed. A case is the dot function where vectors dont have to be of the same dimension and this numpy function tries to get them to fit into another operation such as standard matrix multiplication. I have seen this cause issues such as arrays littered with NaNs.
